### ISSUE TITLE
Error in Vagrant

### ISSUE THREAD

**Issue by emiliodeg** [ovr/perfect-php-vagrant#5] opened 2015-01-21 19:06 UTC
hI, Im traing to install this machine but I can't
every time can access by ssh 
this is the prompt

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Resuming suspended VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...

what can I do?

**Comment by ovr** [comment] 2015-01-22 10:21
Hi

Setup gui to `true` in
https://github.com/ovr/perfect-php-vagrant/blob/master/config.yaml#L5

and run vagrant up, you will the problem

**Comment by emiliodeg** [comment] 2015-01-22 14:10
Thanks but now I have another problem
Hosts.local get crashed
```
    default: /var/www/projects => C:/Users/Emilio/projects
    default: /var/www/localhost => D:/xampp/htdocs/ServiciosArgentinos/perfect-p
hp-vagrant/localhost
    default: /tmp/vagrant-cache => C:/Users/Emilio/.vagrant.d/cache/ubuntu/trust
y64
==> default: Updating /etc/hosts file on active guest machines...
==> default: Updating /etc/hosts file on host machine (password may be required)
...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1375:in `initialize':
Permission denied - C:/Users/Emilio/.vagrant.d/tmp/hosts.local (Errno::EACCES)
        from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1375:in `
open'
        from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1375:in `
block in copy_file'
        from c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1374:in `
open'
..... bla bla bla bla ......
        from c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/b
atch_action.rb:82:in `block (2 levels) in run'

Emilio@EMILIO-PC /d/xampp/htdocs/serviciosargentinos/perfect-php-vagrant (master
)
$ vagrant plugin list
vagrant-cachier (1.2.0)
vagrant-hostmanager (1.5.0)
vagrant-hostsupdater (0.0.11)
vagrant-share (1.1.3, system)

```

I add vagrant-hostupdater plugin (http://stackoverflow.com/questions/16624905/adding-etc-hosts-entry-to-host-machine-on-vagrant-up)  but didnt work

**Comment by ovr** [comment] 2015-01-22 15:17
c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:1375:in `initialize':
Permission denied - C:/Users/Emilio/.vagrant.d/tmp/hosts.local (Errno::EACCES)

Permission denied

**Comment by emiliodeg** [comment] 2015-01-22 16:09
But why Permission denied? I'm on Windows
I tried execute with msysGit, ruby prompt and cmd and every time the same problem
with others VM I dont have any problem :(

**Comment by ovr** [comment] 2015-01-22 16:13
Check owner for hosts.local

**Comment by ovr** [comment] 2015-01-24 10:06
Is closed by
The problem is not related with this project.

**Closed by ovr** 2015-01-24 10:06 UTC
